### ISSUE TITLE
How do you configure the trigger keyword?

### ISSUE THREAD

**Issue by felciano** [giovannicoppola/AlfreDo#1]
The instructions say:

> set the keyword (or hotkey) to create a new task (default: !!!)

Can you please explain how to set this keyword?

**Comment by giovannicoppola** [comment]
@felciano you are right! it got left out at some point, I will reintroduce at the next release. thanks for reporting!
for now, you can just double click on the object below in the workflow configuration and edit the `keyword` field
<img width="200" alt="image" src="https://github.com/giovannicoppola/AlfreDo/assets/5774411/f461fa81-698a-46f9-85ea-b0e434ac80a0">
