### ISSUE TITLE
Cannot add a new task on project if parenthesis is not given

### ISSUE THREAD

**Issue by yangkyeongmo** [giovannicoppola/AlfreDo#14]
# Description

<img width="720" alt="Screenshot 2024-01-24 at 3 59 20 PM" src="https://github.com/giovannicoppola/AlfreDo/assets/24609628/b90b87a0-a597-494f-8290-75cb9fc4988a">

When I add a task by selecting a project in suggestion like above, the task is not added.

<img width="718" alt="Screenshot 2024-01-24 at 4 00 36 PM" src="https://github.com/giovannicoppola/AlfreDo/assets/24609628/b623739c-2819-43f0-bf8f-289db109876b">

But this, adding parenthesis, works for me.

<img width="716" alt="Screenshot 2024-01-24 at 4 06 04 PM" src="https://github.com/giovannicoppola/AlfreDo/assets/24609628/13c05329-7351-4fce-8aeb-e7f7221f075a">

This, adding project before every string, works too tho.

Since the suggestion is given without parenthesis, I was expecting adding to project would work without it.

Thanks for this great workflow btw! :)

**Comment by giovannicoppola** [comment]
@yangkyeongmo because there are no spaces, it should work without parentheses (those are added automatically if there are spaces in the project name). If I understand correctly, in the first screenshot you selected `#Work/Q` from the list of projects, and a task named "some task" was not added?

**Comment by giovannicoppola** [comment]
@yangkyeongmo closing this for now. Let me know if the issue was not resolved. 
BTW, [version 0.4](https://github.com/giovannicoppola/AlfreDo/releases/tag/v0.4) is out with new features. Let me know if you see anything off!

**Comment by yangkyeongmo** [comment]
@giovannicoppola Updating to 0.4 resolved the issue, I guess.
Thanks for your continuous effort in this project!
