### ISSUE TITLE
Can't add a new task

### ISSUE THREAD

**Issue by felciano** [giovannicoppola/AlfreDo#2]
I'm trying to test out AlfreDo. When using the `!!!` keyword to add a task, the Alfred menu shows me that it is correctly matching to "Create new Todoist task". However as soon as I type characters after the space (i.e. after having typed `!!! `) that match disappears and I'm left with the default matches (Search Google, Amazon, Wikipedia). Any suggestions on how to debug this further?

Using AlfreDo 0.2.2 and Alfred 5.1.1

**Comment by giovannicoppola** [comment]
@felciano happy to help, could you share the output of the debugger?

**Comment by giovannicoppola** [comment]
Hi, I am assuming this is fixed? Let me know if not.

**Comment by felciano** [comment]
Hi @giovannicoppola so sorry it looks like I had my Github notifications off. Yes, this issue resolved itself after just uninstalling and reinstalling AlfreDo. I should have followed up and closed the ticket myself--my apologies. I'll re-open if it shows up again.

**Comment by dkapitan** [comment]
I have this issue, using Alfred 5.1.4 and AlfreDo 0.3.1
