### ISSUE TITLE
Can't create tasks

### ISSUE THREAD

**Issue by danepps** [giovannicoppola/AlfreDo#20]
I'm not sure what I'm doing wrong, but whenever I try to create a new task, it looks like it's adding, but then it just doesn't appear in my Todoist account. I have the API setup; AlfreDo can see my tasks in Todoist, and I've forced a refresh. But creating tasks just seems to not actually do anything. Any ideas? Thanks!

**Comment by giovannicoppola** [comment]
@danepps are you pressing return or shift-return? New tasks are created with shift-return

**Comment by danepps** [comment]
I thought I was, but it appears I wasn't. So yes—user error. Sorry and thanks!
