### ISSUE TITLE
Problems with adding new Tasks

### ISSUE THREAD

**Issue by Flusskiesel74** [giovannicoppola/AlfreDo#23]
Hi!
I recognize a funny problem when i try to add a new task von my MacBook (fresh install):
When i type the Trigger (!!!) everything seems to be fine (screenshot), but when i begin the type my task the ,,Create new Todoist taks'' disappears and Alfred will start to make a search with the input (screenshot).

I remember that i had the same problem von my Mac mini, but that changes somehow and now it works all fine. The configuration for AlfredDO is the same on both devices.

Does anyone else know this issue?

Thank You very much in advance!

Yours
Flusskiesel74
<img width="722" alt="Bildschirmfoto 2024-05-22 um 17 36 41" src="https://github.com/giovannicoppola/AlfreDo/assets/170549697/6d605cef-c5c2-4e43-a8ca-13b6dc4f0374">
<img width="714" alt="Bildschirmfoto 2024-05-22 um 17 34 44" src="https://github.com/giovannicoppola/AlfreDo/assets/170549697/9ed36c3f-1727-4a36-9451-bb4f14f98e83">

**Comment by giovannicoppola** [comment]
@Flusskiesel74 have you checked the debugger output?

**Comment by Flusskiesel74** [comment]
Hi!

It is strange: After a few days without any change it works. *Shrug*

**Comment by IevgeniiB** [comment]
Hi! Just adding more data points. I had the same issue, found this ticket, decided to wait for a day and it fixed itself. Right after the installation, I had the same problem as described in the first message.

**Comment by Batistleman** [comment]
Just installed it & have the same issue. 

I triggered this refresh action, then in worked. I guess it needs to make connection with Todoist first?

![CleanShot 2024-09-18 at 09 38 40](https://github.com/user-attachments/assets/ffe93a0d-8061-4d2f-be3e-7fa2a175d3b0)
