### ISSUE TITLE
Question: How to include time in creating a new task?

### ISSUE THREAD

**Issue by zhaokoh** [giovannicoppola/AlfreDo#4]
Hi there,

Thank you for creating such a wonderful Alfred integration. I am trying to set the due date and time for a new task but I was unable to find instructions on how to do so unless I create a task with a date only or without a date, then re-schedule the task using YYYY-MM-DDTHH:mm format.

Is there a way to directly specify the time when creating a new task? Thank you!

**Comment by giovannicoppola** [comment]
@zhaokoh the same format works when [creating a task](https://github.com/giovannicoppola/AlfreDo#creating-new-tasks-).
let me know if you run into problems!

**Comment by zhaokoh** [comment]
Thanks @giovannicoppola. It seems working now. Much appreciated for your help.
