### ISSUE TITLE
Enhancement: Open task in desktop app rather than in a browser

### ISSUE THREAD

**Issue by HalisCz** [giovannicoppola/AlfreDo#5]
Hi there,

first of all, thank you for the AlfreDo, I really like it.

Would you consider adding possibility to open task detail in a Todoist desktop app instead of in a browser?

It seems to me that it should be possible using [URL scheme map](https://developer.todoist.com/guides/#mobile-app-url-schemes). Currently I am able to get my desktop app to open task details using link to specific task in a form `todoist://task?id=11111111111111111111`.

I would love to contribute to the code as well, but I feel there should be some consensus on how to integrate this functionality for people who don't prefer/don't have desktop app. What about using currently unused `Cmd+Enter` on the alfred suggestioned item?

**Comment by giovannicoppola** [comment]
great idea @HalisCz. I think most users would choose one or the other, would you agree? If that is the case, we can set this preference in `Workflow Configuration`

**Comment by giovannicoppola** [comment]
@HalisCz this feature is now added in [Version 3](https://github.com/giovannicoppola/AlfreDo/releases/tag/v0.3)
